name: "Blaze-Job CI"
on: [push, pull_request]
env:
  MAVEN_SKIP_RC: true
jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
# When GitHub Actions supports it: https://github.com/actions/toolkit/issues/399
# We will use the experimental flag as indicator whether a failure should cause a workflow failure
        include:
          - jdk: 17
            build-jdk: 17
    steps:
      - uses: actions/checkout@v2
      - name: Set up Requested JDK
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.jdk }}
          distribution: temurin
      - name: Get year/month for cache key
        id: get-date
        run: |
          echo "::set-output name=yearmonth::$(/bin/date -u "+%Y-%m")"
        shell: bash
      - name: Cache Maven local repository
        uses: actions/cache@v2
        id: cache-maven
        with:
          path: |
            ~/.m2/repository
          # refresh cache every month to avoid unlimited growth
          key: maven-localrepo-${{ steps.get-date.outputs.yearmonth }}
      - name: Set up Maven
        run: ./mvnw -v

      - name: Run build script
        env:
          JDK: ${{ matrix.jdk }}
          BUILD_JDK: ${{ matrix.build-jdk }}
        run: ./ci/build-github.sh
        shell: bash

      - name: Upload test reports (if Maven failed)
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: test-reports-jdk${{ matrix.jdk }}-build-jdk${{ matrix.build-jdk }}
          path: './**/*-reports/'

      - name: Omit produced artifacts from build cache
        run: ./ci/before-cache.sh
